export const enum NoteCategory {
  GENERAL = 'GENERAL',

  TREATMENT = 'TREATMENT',

  HOOF_CARE = 'HOOF_CARE',

  DEHORNING = 'DEHORNING',

  PASTURE_CHANGE = 'PASTURE_CHANGE',

  PASTURE_PLANNED = 'PASTURE_PLANNED',

  WEIGHT = 'WEIGHT',

  WEIGHING0 = 'WEIGHING0',

  WEIGHING200 = 'WEIGHING200',

  WEIGHING365 = 'WEIGHING365',

  ALERT = 'ALERT',

  TEMPER = 'TEMPER',

  ESTRUS = 'ESTRUS',

  INSEMINATION = 'INSEMINATION',
}
